FROM prom/prometheus:latest

ENV PROMETHEUSCONFIGFILE=/etc/prometheus/prometheus.yml
COPY prometheus.yml $PROMETHEUSCONFIGFILE
EXPOSE 9090
CMD ["prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
