global:
  scrape_interval: 30s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: api1
    static_configs:
      - targets: ['game-api1:3000']
  - job_name: api2
    static_configs:
      - targets: ['game-api2:3000']
  - job_name: nginx
    static_configs:
      - targets: ['nginx:80']